
package webservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WSEvento", targetNamespace = "http://webServices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSEvento {


    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg10
     * @param arg11
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @throws EdicionRepetidaException_Exception
     */
    @WebMethod
    @Action(input = "http://webServices/WSEvento/altaEdicionEventoRequest", output = "http://webServices/WSEvento/altaEdicionEventoResponse", fault = {
        @FaultAction(className = EdicionRepetidaException_Exception.class, value = "http://webServices/WSEvento/altaEdicionEvento/Fault/EdicionRepetidaException")
    })
    public void altaEdicionEvento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8,
        @WebParam(name = "arg9", partName = "arg9")
        String arg9,
        @WebParam(name = "arg10", partName = "arg10")
        String arg10,
        @WebParam(name = "arg11", partName = "arg11")
        String arg11)
        throws EdicionRepetidaException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @throws CategoriaEventoVacia_Exception
     * @throws EventoRepetido_Exception
     */
    @WebMethod
    @Action(input = "http://webServices/WSEvento/altaEventoRequest", output = "http://webServices/WSEvento/altaEventoResponse", fault = {
        @FaultAction(className = EventoRepetido_Exception.class, value = "http://webServices/WSEvento/altaEvento/Fault/EventoRepetido"),
        @FaultAction(className = CategoriaEventoVacia_Exception.class, value = "http://webServices/WSEvento/altaEvento/Fault/CategoriaEventoVacia")
    })
    public void altaEvento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        ListOfString arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4)
        throws CategoriaEventoVacia_Exception, EventoRepetido_Exception
    ;

    /**
     * 
     * @return
     *     returns webservices.ListOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSEvento/listarEventosRequest", output = "http://webServices/WSEvento/listarEventosResponse")
    public ListOfString listarEventos();

    /**
     * 
     * @return
     *     returns webservices.ListOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSEvento/listarEventosSinFinalizarRequest", output = "http://webServices/WSEvento/listarEventosSinFinalizarResponse")
    public ListOfString listarEventosSinFinalizar();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.ListOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSEvento/listarEdicionesRequest", output = "http://webServices/WSEvento/listarEdicionesResponse")
    public ListOfString listarEdiciones(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.ListOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSEvento/listarEdicionesAceptadasRequest", output = "http://webServices/WSEvento/listarEdicionesAceptadasResponse")
    public ListOfString listarEdicionesAceptadas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @throws TipoRegistroRepetidoExcepcion_Exception
     */
    @WebMethod
    @Action(input = "http://webServices/WSEvento/crearTipoRegistroRequest", output = "http://webServices/WSEvento/crearTipoRegistroResponse", fault = {
        @FaultAction(className = TipoRegistroRepetidoExcepcion_Exception.class, value = "http://webServices/WSEvento/crearTipoRegistro/Fault/TipoRegistroRepetidoExcepcion")
    })
    public void crearTipoRegistro(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        float arg4,
        @WebParam(name = "arg5", partName = "arg5")
        int arg5)
        throws TipoRegistroRepetidoExcepcion_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns webservices.ListOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSEvento/listarTipoRegistroRequest", output = "http://webServices/WSEvento/listarTipoRegistroResponse")
    public ListOfString listarTipoRegistro(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns webservices.DtTipoRegistro
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSEvento/getDTTipoRegRequest", output = "http://webServices/WSEvento/getDTTipoRegResponse")
    public DtTipoRegistro getDTTipoReg(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.ListOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSEvento/listarCategoriasRequest", output = "http://webServices/WSEvento/listarCategoriasResponse")
    public ListOfString listarCategorias(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns webservices.ListOfString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSEvento/getCategoriasRequest", output = "http://webServices/WSEvento/getCategoriasResponse")
    public ListOfString getCategorias();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtEvento
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSEvento/getDTEventoRequest", output = "http://webServices/WSEvento/getDTEventoResponse")
    public DtEvento getDTEvento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://webServices/WSEvento/finalizarEventoRequest", output = "http://webServices/WSEvento/finalizarEventoResponse")
    public void finalizarEvento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @throws CupoLlenoExcepcion_Exception
     * @throws YaRegistradoExcepcion_Exception
     */
    @WebMethod
    @Action(input = "http://webServices/WSEvento/altaRegistroRequest", output = "http://webServices/WSEvento/altaRegistroResponse", fault = {
        @FaultAction(className = YaRegistradoExcepcion_Exception.class, value = "http://webServices/WSEvento/altaRegistro/Fault/YaRegistradoExcepcion"),
        @FaultAction(className = CupoLlenoExcepcion_Exception.class, value = "http://webServices/WSEvento/altaRegistro/Fault/CupoLlenoExcepcion")
    })
    public void altaRegistro(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4)
        throws CupoLlenoExcepcion_Exception, YaRegistradoExcepcion_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns webservices.DtEdicion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSEvento/getDTEdicionRequest", output = "http://webServices/WSEvento/getDTEdicionResponse")
    public DtEdicion getDTEdicion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns webservices.DtRegistro
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSEvento/getRegistroRequest", output = "http://webServices/WSEvento/getRegistroResponse")
    public DtRegistro getRegistro(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://webServices/WSEvento/sumarVisitaRequest", output = "http://webServices/WSEvento/sumarVisitaResponse")
    public void sumarVisita(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     */
    @WebMethod
    @Action(input = "http://webServices/WSEvento/marcarAsistenciaRequest", output = "http://webServices/WSEvento/marcarAsistenciaResponse")
    public void marcarAsistencia(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSEvento/getImagenEventoRequest", output = "http://webServices/WSEvento/getImagenEventoResponse")
    public byte[] getImagenEvento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSEvento/getImagenEdicionRequest", output = "http://webServices/WSEvento/getImagenEdicionResponse")
    public byte[] getImagenEdicion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

}
