
package webservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WSUsuario", targetNamespace = "http://webServices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSUsuario {


    /**
     * 
     * @return
     *     returns webservices.SetOfDTOrganizador
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuario/listarOrganizadoresRequest", output = "http://webServices/WSUsuario/listarOrganizadoresResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/listarOrganizadores/Fault/UsuarioNoExisteException")
    })
    public SetOfDTOrganizador listarOrganizadores()
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg10
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @throws ContrasenaInvalidaException_Exception
     * @throws UsuarioCorreoRepetidoException_Exception
     * @throws UsuarioRepetidoException_Exception
     */
    @WebMethod
    @Action(input = "http://webServices/WSUsuario/registrarUsuarioConContrasenaRequest", output = "http://webServices/WSUsuario/registrarUsuarioConContrasenaResponse", fault = {
        @FaultAction(className = UsuarioRepetidoException_Exception.class, value = "http://webServices/WSUsuario/registrarUsuarioConContrasena/Fault/UsuarioRepetidoException"),
        @FaultAction(className = UsuarioCorreoRepetidoException_Exception.class, value = "http://webServices/WSUsuario/registrarUsuarioConContrasena/Fault/UsuarioCorreoRepetidoException"),
        @FaultAction(className = ContrasenaInvalidaException_Exception.class, value = "http://webServices/WSUsuario/registrarUsuarioConContrasena/Fault/ContrasenaInvalidaException")
    })
    public void registrarUsuarioConContrasena(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        boolean arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8,
        @WebParam(name = "arg9", partName = "arg9")
        String arg9,
        @WebParam(name = "arg10", partName = "arg10")
        String arg10)
        throws ContrasenaInvalidaException_Exception, UsuarioCorreoRepetidoException_Exception, UsuarioRepetidoException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @throws UsuarioCorreoRepetidoException_Exception
     * @throws UsuarioRepetidoException_Exception
     */
    @WebMethod
    @Action(input = "http://webServices/WSUsuario/registrarUsuarioRequest", output = "http://webServices/WSUsuario/registrarUsuarioResponse", fault = {
        @FaultAction(className = UsuarioRepetidoException_Exception.class, value = "http://webServices/WSUsuario/registrarUsuario/Fault/UsuarioRepetidoException"),
        @FaultAction(className = UsuarioCorreoRepetidoException_Exception.class, value = "http://webServices/WSUsuario/registrarUsuario/Fault/UsuarioCorreoRepetidoException")
    })
    public void registrarUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        boolean arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7)
        throws UsuarioCorreoRepetidoException_Exception, UsuarioRepetidoException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtUsuario
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuario/getUsuarioRequest", output = "http://webServices/WSUsuario/getUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/getUsuario/Fault/UsuarioNoExisteException")
    })
    public DtUsuario getUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.ListOfString
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuario/listarNombresRegistrosDeUsuarioRequest", output = "http://webServices/WSUsuario/listarNombresRegistrosDeUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/listarNombresRegistrosDeUsuario/Fault/UsuarioNoExisteException")
    })
    public ListOfString listarNombresRegistrosDeUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns webservices.DtUsuario
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuario/verInfoUsuarioRequest", output = "http://webServices/WSUsuario/verInfoUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/verInfoUsuario/Fault/UsuarioNoExisteException")
    })
    public DtUsuario verInfoUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        boolean arg1)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns webservices.SetOfDTUsuario
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuario/listarUsuariosRequest", output = "http://webServices/WSUsuario/listarUsuariosResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/listarUsuarios/Fault/UsuarioNoExisteException")
    })
    public SetOfDTUsuario listarUsuarios()
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns webservices.SetOfDTAsistente
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuario/listarAsistentesRequest", output = "http://webServices/WSUsuario/listarAsistentesResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/listarAsistentes/Fault/UsuarioNoExisteException")
    })
    public SetOfDTAsistente listarAsistentes()
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns webservices.DtRegistro
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuario/obtenerRegistroDeUsuarioRequest", output = "http://webServices/WSUsuario/obtenerRegistroDeUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/obtenerRegistroDeUsuario/Fault/UsuarioNoExisteException")
    })
    public DtRegistro obtenerRegistroDeUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.HashMap
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuario/listarRegistrosEdicionRequest", output = "http://webServices/WSUsuario/listarRegistrosEdicionResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/listarRegistrosEdicion/Fault/UsuarioNoExisteException")
    })
    public HashMap listarRegistrosEdicion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtOrganizador
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuario/obtenerInfoOrganizadorRequest", output = "http://webServices/WSUsuario/obtenerInfoOrganizadorResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/obtenerInfoOrganizador/Fault/UsuarioNoExisteException")
    })
    public DtOrganizador obtenerInfoOrganizador(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtUsuario
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuario/getUsuarioPorCorreoRequest", output = "http://webServices/WSUsuario/getUsuarioPorCorreoResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/getUsuarioPorCorreo/Fault/UsuarioNoExisteException")
    })
    public DtUsuario getUsuarioPorCorreo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuario/obtenerNicknamePorEmailRequest", output = "http://webServices/WSUsuario/obtenerNicknamePorEmailResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/obtenerNicknamePorEmail/Fault/UsuarioNoExisteException")
    })
    public String obtenerNicknamePorEmail(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuario/verificarContrasenaRequest", output = "http://webServices/WSUsuario/verificarContrasenaResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/verificarContrasena/Fault/UsuarioNoExisteException")
    })
    public boolean verificarContrasena(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuario/obtenerRolRequest", output = "http://webServices/WSUsuario/obtenerRolResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/obtenerRol/Fault/UsuarioNoExisteException")
    })
    public String obtenerRol(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @throws ContrasenaInvalidaException_Exception
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://webServices/WSUsuario/modificarUsuarioRequest", output = "http://webServices/WSUsuario/modificarUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/modificarUsuario/Fault/UsuarioNoExisteException"),
        @FaultAction(className = ContrasenaInvalidaException_Exception.class, value = "http://webServices/WSUsuario/modificarUsuario/Fault/ContrasenaInvalidaException")
    })
    public void modificarUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6)
        throws ContrasenaInvalidaException_Exception, UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://webServices/WSUsuario/seguirUsrRequest", output = "http://webServices/WSUsuario/seguirUsrResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/seguirUsr/Fault/UsuarioNoExisteException")
    })
    public void seguirUsr(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://webServices/WSUsuario/dejarDeSeguirUsrRequest", output = "http://webServices/WSUsuario/dejarDeSeguirUsrResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/dejarDeSeguirUsr/Fault/UsuarioNoExisteException")
    })
    public void dejarDeSeguirUsr(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuario/verificarSiSigueRequest", output = "http://webServices/WSUsuario/verificarSiSigueResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/verificarSiSigue/Fault/UsuarioNoExisteException")
    })
    public boolean verificarSiSigue(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.SetOfDTUsuario
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuario/obtenerUsuariosSeguidosRequest", output = "http://webServices/WSUsuario/obtenerUsuariosSeguidosResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/obtenerUsuariosSeguidos/Fault/UsuarioNoExisteException")
    })
    public SetOfDTUsuario obtenerUsuariosSeguidos(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuario/getImagenUsuarioRequest", output = "http://webServices/WSUsuario/getImagenUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/getImagenUsuario/Fault/UsuarioNoExisteException")
    })
    public byte[] getImagenUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webServices/WSUsuario/pingRequest", output = "http://webServices/WSUsuario/pingResponse")
    public String ping();

    /**
     * 
     * @param arg0
     * @param arg1
     * @throws ContrasenaInvalidaException_Exception
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://webServices/WSUsuario/modificarImagenPerfilRequest", output = "http://webServices/WSUsuario/modificarImagenPerfilResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webServices/WSUsuario/modificarImagenPerfil/Fault/UsuarioNoExisteException"),
        @FaultAction(className = ContrasenaInvalidaException_Exception.class, value = "http://webServices/WSUsuario/modificarImagenPerfil/Fault/ContrasenaInvalidaException")
    })
    public void modificarImagenPerfil(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws ContrasenaInvalidaException_Exception, UsuarioNoExisteException_Exception
    ;

}
