
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WSUsuarioService", targetNamespace = "http://webServices/", wsdlLocation = "http://localhost:1234/evtuy/usuarios?wsdl")
public class WSUsuarioService
    extends Service
{

    private final static URL WSUSUARIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSUSUARIOSERVICE_EXCEPTION;
    private final static QName WSUSUARIOSERVICE_QNAME = new QName("http://webServices/", "WSUsuarioService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1234/evtuy/usuarios?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSUSUARIOSERVICE_WSDL_LOCATION = url;
        WSUSUARIOSERVICE_EXCEPTION = e;
    }

    public WSUsuarioService() {
        super(__getWsdlLocation(), WSUSUARIOSERVICE_QNAME);
    }

    public WSUsuarioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSUSUARIOSERVICE_QNAME, features);
    }

    public WSUsuarioService(URL wsdlLocation) {
        super(wsdlLocation, WSUSUARIOSERVICE_QNAME);
    }

    public WSUsuarioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSUSUARIOSERVICE_QNAME, features);
    }

    public WSUsuarioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSUsuarioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSUsuario
     */
    @WebEndpoint(name = "WSUsuarioPort")
    public WSUsuario getWSUsuarioPort() {
        return super.getPort(new QName("http://webServices/", "WSUsuarioPort"), WSUsuario.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSUsuario
     */
    @WebEndpoint(name = "WSUsuarioPort")
    public WSUsuario getWSUsuarioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices/", "WSUsuarioPort"), WSUsuario.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSUSUARIOSERVICE_EXCEPTION!= null) {
            throw WSUSUARIOSERVICE_EXCEPTION;
        }
        return WSUSUARIOSERVICE_WSDL_LOCATION;
    }

}
