
package webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "CategoriaEventoVacia", targetNamespace = "http://webServices/")
public class CategoriaEventoVacia_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CategoriaEventoVacia faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CategoriaEventoVacia_Exception(String message, CategoriaEventoVacia faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public CategoriaEventoVacia_Exception(String message, CategoriaEventoVacia faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservices.CategoriaEventoVacia
     */
    public CategoriaEventoVacia getFaultInfo() {
        return faultInfo;
    }

}
