
package webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "EventoRepetido", targetNamespace = "http://webServices/")
public class EventoRepetido_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EventoRepetido faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EventoRepetido_Exception(String message, EventoRepetido faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public EventoRepetido_Exception(String message, EventoRepetido faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservices.EventoRepetido
     */
    public EventoRepetido getFaultInfo() {
        return faultInfo;
    }

}
