
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WSEventoService", targetNamespace = "http://webServices/", wsdlLocation = "http://localhost:1234/evtuy/eventos?wsdl")
public class WSEventoService
    extends Service
{

    private final static URL WSEVENTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSEVENTOSERVICE_EXCEPTION;
    private final static QName WSEVENTOSERVICE_QNAME = new QName("http://webServices/", "WSEventoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1234/evtuy/eventos?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSEVENTOSERVICE_WSDL_LOCATION = url;
        WSEVENTOSERVICE_EXCEPTION = e;
    }

    public WSEventoService() {
        super(__getWsdlLocation(), WSEVENTOSERVICE_QNAME);
    }

    public WSEventoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSEVENTOSERVICE_QNAME, features);
    }

    public WSEventoService(URL wsdlLocation) {
        super(wsdlLocation, WSEVENTOSERVICE_QNAME);
    }

    public WSEventoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSEVENTOSERVICE_QNAME, features);
    }

    public WSEventoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSEventoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSEvento
     */
    @WebEndpoint(name = "WSEventoPort")
    public WSEvento getWSEventoPort() {
        return super.getPort(new QName("http://webServices/", "WSEventoPort"), WSEvento.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSEvento
     */
    @WebEndpoint(name = "WSEventoPort")
    public WSEvento getWSEventoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices/", "WSEventoPort"), WSEvento.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSEVENTOSERVICE_EXCEPTION!= null) {
            throw WSEVENTOSERVICE_EXCEPTION;
        }
        return WSEVENTOSERVICE_WSDL_LOCATION;
    }

}
